name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # Run on Windows

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'  # Latest Node.js LTS version
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build Library with Rollup
        run: npm run build

      - name: Build Storybook
        run: npm run build-storybook 

      - name: List Project Directory
        run: dir  # Windows command to list files in the root directory

      - name: List Build Output
        run: dir storybook-static  # Check if the directory exists

      - name: Change Permissions for Storybook Build
        run: icacls storybook-static /grant Everyone:(OI)(CI)F  # Give all permissions to the storybook-static directory
        
      - name: Upload Storybook Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: storybook-static
          path: storybook-static/**

  deploy-prod:
    runs-on: windows-latest  # Run on Windows
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Download Storybook Artifacts
        uses: actions/download-artifact@v4
        with:
          name: storybook-static 

      - name: List Downloaded Artifacts
        run: dir  # Windows command to list files in the current directory

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy to Vercel (Production)
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          TEAM_TOKEN: ${{ secrets.TEAM_TOKEN }}
        run: |
          vercel --prod --yes --token "$VERCEL_TOKEN" --team "$TEAM_TOKEN" storybook-static

  publish:
    runs-on: windows-latest  # Run on Windows
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'  # Latest Node.js LTS version

      - name: Install dependencies
        run: npm install

      - name: Build Library
        run: npm run build

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish
