name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Run Tests with Coverage Threshold
        run: npm run test 
        env:
          CI: true

  build:
    runs-on: windows-latest
    needs: test  # Ensures this job runs only if 'test' succeeds

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build Library with Rollup
        run: npm run build

      - name: Build Storybook
        run: npm run build-storybook

      - name: Upload Storybook Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: storybook-static
          path: storybook-static/**

      - name: Upload Built Library Artifact
        uses: actions/upload-artifact@v4
        with:
          name: library-build
          path: lib/**

  deploy-dev:
    runs-on: windows-latest
    needs: [build]  # Ensures this job runs only if 'build' succeeds

    steps:
      - name: Download Storybook Artifacts
        uses: actions/download-artifact@v4
        with:
          name: storybook-static

      - name: Install Vercel CLI
        run: npm install --legacy-peer-deps -g vercel

      - name: Deploy to Vercel (Development)
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          TEAM_TOKEN: ${{ secrets.TEAM_TOKEN }}
        run: |
          vercel --yes --token "${{ secrets.VERCEL_TOKEN }}" --team "${{ secrets.TEAM_TOKEN }}" ./

  deploy-prod:
    runs-on: windows-latest
    needs: [build]  # Ensures this job runs only if 'build' succeeds
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download Storybook Artifacts
        uses: actions/download-artifact@v4
        with:
          name: storybook-static

      - name: Install Vercel CLI
        run: npm install --legacy-peer-deps -g vercel

      - name: Deploy to Vercel (Production)
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          TEAM_TOKEN: ${{ secrets.TEAM_TOKEN }}
        run: |
          vercel --prod --yes --token "${{ secrets.VERCEL_TOKEN }}" --team "${{ secrets.TEAM_TOKEN }}" ./

  publish:
    runs-on: windows-latest
    needs: [build]  # Ensures this job runs only if 'build' succeeds
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build Library
        run: npm run build

      - name: Configure npm for Publishing
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm config set @adit-design-system:registry https://registry.npmjs.org/
          npm config set //registry.npmjs.org/:_authToken "${{ secrets.NPM_TOKEN }}"

      - name: Publish to npm
        run: npm publish
